# install-services.yml

---
  - hosts: tag_layer_alb
    become: true
    tasks:
      - name: installing apache
        yum: name=httpd state=present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes

  - hosts: tag_layer_web
    become: true
    tasks:
      - name: installing apache
        yum: 
          name:
            - httpd
            - php
          state: present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes